<?php
/** @var string $ticket_id */
include __DIR__ . '/header.php' ?>
	
	<header class="page-header">
		<h1 class="page-header-title clearfix text-center">
			<a class="btn btn-link float-left" href="/"><i class="fas fa-chevron-left"></i> 戻る</a>
			<sapn>チケット情報</sapn>
		</h1>
	</header>
	
	<hr />

	<div class="ticket-wrapper">
		<div id="ticket" data-ticket-id="<?php echo htmlspecialchars( $ticket_id, ENT_QUOTES ) ?>"></div>
	</div>

<?php include __DIR__ . '/footer.php';
