<?php include __DIR__ . '/header.php' ?>

    <header class="page-header">
        <h1 class="page-header-title">チケットデータインポート</h1>
        <p class="lead">WordCampのCSVからチケットデータをインポートします</p>
    </header>

    <hr />

    <form class="" action="/import" method="post" enctype="multipart/form-data">
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="ticket-csv" name="ticket-csv">
            <label class="custom-file-label" for="ticket-csv">CSVを選択</label>
        </div>
        <p class="text-center mt-3">
            <input class="btn btn-lg btn-outline-primary" type="submit" value="送信" />
        </p>
    </form>

<?php include __DIR__ . '/footer.php';
